name: Synchronize JJMarin-08345 with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to semillero
        run: |
          git checkout -b JJMarin-08345
          git push semillero JJMarin-08345:main
        env:
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: <your-email@example.com>
